development:
  facebook:
    token: <%= ENV['FACEBOOK_TOKEN'] %>
    key: <%= ENV['FACEBOOK_KEY'] %>
  twitter:
    token: <%= ENV['TWITTER_TOKEN'] %>
    key: <%= ENV['TWITTER_KEY'] %>
production:
  facebook:
    token: <%= ENV['FACEBOOK_TOKEN'] %>
    key: <%= ENV['FACEBOOK_KEY'] %>
  twitter:
    token: <%= ENV['TWITTER_TOKEN'] %>
    key: <%= ENV['TWITTER_KEY'] %>
test:
  facebook:
    token: <%= ENV['FACEBOOK_TOKEN'] %>
    key: <%= ENV['FACEBOOK_KEY'] %>
  twitter:
    token: <%= ENV['TWITTER_TOKEN'] %>
    key: <%= ENV['TWITTER_KEY'] %>
