development:
  facebook:
    token: <%= ENV['FACEBOOK_TOKEN'] %>
    key: <%= ENV['FACEBOOK_KEY'] %>

production:
  facebook:
    token: <%= ENV['FACEBOOK_TOKEN'] %>
    key: <%= ENV['FACEBOOK_KEY'] %>

test:
  facebook:
    token: <%= ENV['FACEBOOK_TOKEN'] %>
    key: <%= ENV['FACEBOOK_KEY'] %>
